apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "cluster-demo-install"
  environment:
    cluster_type: ec2
    domain: ec2.enviroment.platform.vee.codes
    ingress_type: nginx
    public_ip: 18.233.50.217
  annotations:
    github.com/project-slug: veecode-apr/cluster-demo-install
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml,deploy-dashboard
    cluster/instructions: "# Run the following commands to import the kubeconfig:\n  ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@$18.233.50.217 \"mkdir -p .kube && k3d kubeconfig get k3s > ~/.kube/config\"\n  scp -i ./cert.pem $USERNAME@$18.233.50.217:~/.kube/config ~/.kube/config-cluster-demo-install\n  yq -e 'del(.clusters[0].cluster.certificate-authority-data) | .clusters[0].cluster.insecure-skip-tls-verify=true | .clusters[].cluster.server |= sub(\"0.0.0.0\", \"18.233.50.217\")' -i ~/.kube/config-cluster-demo-install\n  export KUBECONFIG=~/.kube/config-cluster-demo-install\n  kubectl get pods -A\n"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/ec2_environment'
